version: '3'
services:
    # client:
    #     build:
    #         context: ./client
    #     ports:
    #         - '3001:3000'
    #     environment: 
    #         - REACT_APP_API_URL=http://localhost:5001/api
    #     depends_on:
    #         - server
    #     volumes:
    #         - ./client:/app/
    #         - /app/node_modules
    server:
        build:
            context: ./server
        ports:
            - '5001:5000'
        environment:
            - PGDATABASE=note_to_self
            - PGHOST=db
        volumes:
            - ./server:/app/
            - /app/node_modules
    db:
        build:
            context: ./db
        volumes:
            - note_to_self:/var/lib/postgresql/data
        ports:
            - '5433:5432'
volumes:
    note_to_self:
